acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

acme1_website:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

home:
   path:   /
   defaults: { _controller: AcmeBlogBundle:Blog:home }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_resetting_request:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_security_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /login
    defaults: { _controller: FOSUserBundle:Security:login }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin
