acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

acme1_website:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

home:
   path:   /
   defaults: { _controller: AcmeBlogBundle:Blog:home }

