acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

acme1_website:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

home:
   path:   /
   defaults: { _controller: AcmeBlogBundle:Blog:home }

#FosUserBundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting_request:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_security_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /login
    defaults: { _controller: FOSUserBundle:Security:login }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

vkontakte_login:
    pattern: /login/check-vkontakte

facebook_login:
    pattern: /login/check-facebook
