Blog_show:
    path:  /{id}
    defaults: { _controller: AcmeHelloBundle:Page:show}
    requirements:
        _method:  GET|POST
        id: \d+

Blog_homepage:
    path:  /{_locale}
    defaults: { _controller: AcmeHelloBundle:Page:index}
    requirements:
        _locale: en|uk

Blog_contact:
    path:  /contact/{_locale}
    defaults: { _controller: AcmeHelloBundle:Page:contact}
    requirements:
        _method:  GET|POST
        _locale: en|uk

Blog_about:
    path:  /about/{_locale}
    defaults: { _controller: AcmeHelloBundle:Page:about}
    requirements:
        _locale: en|uk


Blog_admin:
     path:  /admin
     defaults: { _controller: AcmeHelloBundle:Page:admin}
