services:
    acme.hello.menu.voter.request:
        class: Acme\HelloBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }

#parameters:
#    my_user_provider.class: Acme\HelloBundle\Admin\FOSUBUserProvider
#
#services:
#    my_user_provider:
#        class: "%my_user_provider.class%"
#        #this is the place where the properties are passed to the UserProvider - see config.yml
#        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
