blog_show_home:
    path:      /blog/stas
    defaults:  { _controller: AcmeBlogBundle:Blog:stas }

blog_show_user:
    path:      /blog/{slug}
    defaults:  { _controller: AcmeBlogBundle:Blog:show }
    requirements:
#            slug:  \d+

show_page:
    path:       /blog/page
    defaults:   { _controller: AcmeBlogBundle:Blog:home }

