blog_show_home:
    path:      /blog/stas
    defaults:  { _controller: AcmeBlogBundle:Blog:stas }

blog_show_user:
    path:      /blog/{slug}
    defaults:  { _controller: AcmeBlogBundle:Default:show }
    requirements:
            slug:  \d+

show_page:
    path:       /blog/page
    defaults:   { _controller: AcmeBlogBundle:Blog:home }

new_car:
    path:       /car/new
    defaults:   { _controller: AcmeBlogBundle:Default:create }

show_bd:
    path:       /car/new
    defaults:   { _controller: AcmeBlogBundle:Blog:home }

